Repository DeveloperAcademy-POSTECH/MC3-Team17-ForJaeRin, pull requests merged in 2023-07, with the labels that each got.

#7 [Setting] 프로젝트 디렉토리 구조 세팅 #1
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/ContentView.swift
  ForJaeRin/Data/sample.json
  ForJaeRin/Global/Extension/View+Extension.swift
  ForJaeRin/Global/Modifier/FontModifier.swift
  ForJaeRin/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/test_landscape.imageset/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/test_landscape.imageset/test_landscape.jpeg
  ForJaeRin/Models/Protocol/SampleProtocol.swift
  ForJaeRin/Models/SampleModel.swift
  ForJaeRin/Presentation/ViewModels/SampleVM.swift
  ForJaeRin/Presentation/Views/SampleView/SampleView.swift
Labels: Setting

#16 [Test]: FileSystem 기능 테스트
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/ContentView.swift
  ForJaeRin/Presentation/Views/Components/ButtonView/ButtonView.swift
  ForJaeRin/Presentation/Views/TestView/FileSystemView/FileSystemView.swift
  ForJaeRin/Utils/AppFileManager.swift
Labels: Setting, Test

#29 [Setting]: 컬러 시스템 추가
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/App/ForJaeRinApp.swift
  ForJaeRin/Global/Extension/Color+Extension.swift
  ForJaeRin/Presentation/Views/Components/ToolbarView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
Labels: Setting

#30 [Feat]: 프로젝트 데이터 모델링
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/PDFModels/PDFDocumentManager.swift
  ForJaeRin/Models/PDFModels/PDFGroupModel.swift
  ForJaeRin/Models/PDFModels/PDFPageModel.swift
  ForJaeRin/Models/ProjectModels/PracticeModel.swift
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Models/ProjectModels/ProjectMetadataModel.swift
  ForJaeRin/Presentation/Views/SplitLayoutView/SplitLayoutView+Extension.swift
  ForJaeRin/Presentation/Views/SplitLayoutView/SplitLayoutView.swift
Labels: Feat

#32 [Feat]: 그룹 수정하기 뷰 작성
  .swiftlint.yml
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/App/ContentView.swift
  ForJaeRin/App/ForJaeRinApp.swift
  ForJaeRin/Global/Extension/Color+Extension.swift
  ForJaeRin/Global/Modifier/CustomLabel.swift
  ForJaeRin/Global/Resources/SampleProject/sampleProject.json
  ForJaeRin/Models/PDFModels/PDFDocumentManager.swift
  ForJaeRin/Models/PDFModels/PDFPageModel.swift
  ForJaeRin/Models/ProjectModels/PracticeModel.swift
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/Components/ChipView.swift
  ForJaeRin/Presentation/Views/Components/PDFView/PDFView.swift
  ForJaeRin/Presentation/Views/Components/ToolbarView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationPDFView/PresentationPDFView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListOnboardingView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
  ForJaeRin/Presentation/Views/SplitLayoutView/SplitLayoutView+Extension.swift
  ForJaeRin/Presentation/Views/SplitLayoutView/SplitLayoutView.swift
  ForJaeRin/Presentation/Views/TestView/ProjectView/ProjectTestView.swift
  ForJaeRin/Utils/AppFileManager.swift
Labels: Feat

#41 [Feat] 문서기반 변경 - 테스트 후 기존 플로우로 변경
  .swiftlint.yml
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForJaeRin/App/ContentView.swift
  ForJaeRin/App/ForJaeRin.entitlements
  ForJaeRin/App/ForJaeRinApp.swift
  ForJaeRin/Data/sample.json
  ForJaeRin/Global/Extension/Color+Extension.swift
  ForJaeRin/Global/Extension/Font+Extension.swift
  ForJaeRin/Global/Modifier/ButtonModifier.swift
  ForJaeRin/Global/Modifier/CustomLabel.swift
  ForJaeRin/Global/Modifier/FontModifier.swift
  ForJaeRin/Info.plist
  ForJaeRin/Models/KkoFileModels/KkoFileModel.swift
  ForJaeRin/Models/SampleModel.swift
  ForJaeRin/Presentation/Scenes/SelectProjectScene.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/HomeVM.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPdfView/ImportPdfView.swift
  ForJaeRin/Presentation/Views/HomeView/ProjectCardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
  ForJaeRin/Presentation/Views/SplitLayoutView/SplitLayoutView+Extension.swift
  ForJaeRin/Presentation/Views/SplitLayoutView/SplitLayoutView.swift
  ForJaeRin/Presentation/Views/TestView/FileSystemView/FileSystemView.swift
  ForJaeRin/Presentation/Views/TestView/RecordView/RecordView.swift
  ForJaeRin/Presentation/Views/TestView/SampleView/SampleView.swift
  ForJaeRin/Presentation/Views/TestView/SelectProjectView/SelectProjectView.swift
  ForJaeRin/Utils/AppFileDocument.swift
  ForJaeRin/Utils/DateManager.swift
Labels: Feat

#43 [feat] #21 - keyword관련 구현 90프로 완료
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Extension/String+Extension.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordFieldView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
Labels: Feat

#45 [Feat]: PDF 로딩 + 정보입력 90%
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputScriptView.swift
Labels: Feat

#46 [Feat]: KeywordView 병합, 레이아웃 수정, 미사용 코드 삭제
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/App/ForJaeRinApp.swift
  ForJaeRin/Global/Extension/Color+Extension.swift
  ForJaeRin/Global/Extension/String+Extension.swift
  ForJaeRin/Global/Modifier/ButtonModifier.swift
  ForJaeRin/Global/Modifier/CustomLabel.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectDocumentVM.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationProgressView/PresentationProgressView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordFieldView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListOnboardingView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
Labels: Feat, Del

#47 [Fix]: 프로젝트 로딩 및 정보 입력 코드 수정
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputScriptView.swift
Labels: Fix

#49 [Feat]: PresentationPageListItem 파일에 PDF화면 이미지로 바꾸기
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
Labels: Feat

#51 [Feat]: PresentationPageListItem에 스크립트 연동
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
Labels: Feat

#53 [Feat] PresentationPageListItem에 스크립트 연동
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordFieldView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
Labels: Feat

#54 [Feat]: 연습모드 뷰 작성
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/App/ForJaeRinApp.swift
  ForJaeRin/Global/Extension/Color+Extension.swift
  ForJaeRin/Global/Extension/Font+Extension.swift
  ForJaeRin/Models/ProjectModels/PracticeModel.swift
  ForJaeRin/Presentation/Views/Components/PDFView/PDFView.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationProgressView/PresentationProgressView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/VoiceVisualizationView/VoiceVisualizationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
Labels: Chore, Feat

#55 Feat/#34 그룹화 성공
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupListView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupingAddButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/TempPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
Labels: Feat

#57 [Fix] PDF 불러오기 과정에서 그룹 지정하는 화면 PDF이미지로 뜨게 변경
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/TempPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
Labels: Fix

#59 [Fix] ImportPDFView 기능 제외 디테일 수정
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/TempPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputScriptView.swift
Labels: Fix

#60 [FIX] #44 - 버그수정
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordFieldView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
Labels: Fix

#61 Feat/#38 흐름보기 뷰
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/Views/ProjectView/ProjectFlowView/ProjectFlowView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
Labels: Feat

#62 [Feat]: 프레젠테이션 뷰 작성
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/ViewModels/ProjectVM/PresentationVM.swift
  ForJaeRin/Presentation/Views/Components/PDFView/PDFView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationPDFView/PresentationPDFView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationProgressView/PresentationProgressView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/VoiceVisualizationView/VoiceVisualizationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectFlowView/ProjectFlowView.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Feat

#65 Feat/#23
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupListView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
Labels: Feat

#67 [Fix] SettingGroupView와 MyData와 연동
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupListView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupingAddButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
Labels: Fix

#68 [Refactor]: ProjectFlowView 코드 정리
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Extension/Type+Extension.swift
  ForJaeRin/Models/PDFModels/PDFDocumentManager.swift
  ForJaeRin/Models/ProjectModels/PracticeModel.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/HomeVM.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectFlowVM.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectFlowView/ProjectFlowView.swift
Labels: Refactor

#69 [Refactor]: PresentationView 코드 정리
  ForJaeRin/Presentation/ViewModels/ProjectVM/PresentationVM.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectDocumentVM.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectFlowVM.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationPDFView/PresentationPDFView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationProgressView/PresentationProgressView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/VoiceVisualizationView/VoiceVisualizationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectFlowView/ProjectFlowView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Refactor

#72 [Feat]: HistoryView 작성
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryListView/ProjectHistoryListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/ProjectSummaryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/plus.png
Labels: Feat

#73 [Feat] 새 프로젝트 생성 후 데이터 저장
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Models/PDFModels/PDFDocumentManager.swift
  ForJaeRin/Models/PDFModels/PDFGroupModel.swift
  ForJaeRin/Models/PDFModels/PDFPageModel.swift
  ForJaeRin/Models/ProjectModels/PracticeModel.swift
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Models/ProjectModels/ProjectMetadataModel.swift
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Utils/AppFileManager.swift
Labels: Feat

#74 Feat/#20
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Info.plist
  ForJaeRin/Models/ProjectModels/PracticeModel.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/PresentationVM.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/ProjectSummaryView.swift
  ForJaeRin/Utils/SpeechRecognizer.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Feat

#76 [Refactor]: ImportPDFView 코드 리팩토링
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Extension/Color+Extension.swift
  ForJaeRin/Global/Resources/SampleProject/sampleProject.json
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Models/ProjectModels/ProjectMetadataModel.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/GroupListVM.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/HomeVM.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/ImportPDFVM.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/SettingGroupVM.swift
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupListView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupingAddButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/TempPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputScriptView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
  ForJaeRin/Utils/AppFileManager.swift
Labels: Refactor

#77 [Add]: 앱 아이콘 추가
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_1024.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_256.png
  ForJaeRin/Global/Resources/Assets.xcassets/logo_main.imageset/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/logo_main.imageset/logo_main.svg
  ForJaeRin/Models/PDFModels/PDFDocumentManager.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/HomeVM.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
Labels: Add

#78 Feat/#75
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Resources/SampleProject/sampleProject.json
  ForJaeRin/Presentation/ViewModels/ProjectVM/PresentationVM.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectHistoryVM.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryListView/ProjectHistoryListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/ProjectSummaryView.swift
  ForJaeRin/Utils/AppFileManager.swift
  ForJaeRin/Utils/SpeechRecognizer.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Feat

#80 Feat/#75
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Resources/SampleProject/sampleProject.json
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectHistoryVM.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryListView/ProjectHistoryListView.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Feat

#81 [Refactor]: ProjectHistoryView 정리
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_128.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_16.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_256 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_32 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_32.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_64.png
  ForJaeRin/Models/PDFModels/PDFDocumentManager.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/ImportPDFVM.swift
  ForJaeRin/Presentation/Views/Components/RoundedCornerView.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationPDFView/PresentationPDFView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/MissedKeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/PracticeSummaryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryListView/ProjectHistoryListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/CustomBarChartView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/GroupChartView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/GroupView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/PieChartView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/ProjectSummaryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/StyleDetailChartView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
Labels: Refactor

#85 [Feat] 발표 정보 저장하고 불러오기
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/App/ForJaeRinApp.swift
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/TempPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
  ForJaeRin/Presentation/Views/HomeView/ProjectCardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
  ForJaeRin/Utils/AppFileManager.swift
Labels: Feat

#88 Add/#82 연습기록보기 마무리
  ForJaeRin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForJaeRin/Global/Resources/SampleProject/sampleProject.json
  ForJaeRin/Presentation/ViewModels/ProjectVM/PresentationVM.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectHistoryVM.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/MissedKeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/PracticeSummaryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryListView/ProjectHistoryListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryView.swift
Labels: Add

#89 [Refactor] 발표정보 저장/불러오기 코드 수정
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Utils/AppFileManager.swift
Labels: Refactor

#91 [Feat]: PracticeDashboardView 작성
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ForJaeRin/Global/Extension/Color+Extension.swift
  ForJaeRin/Global/Modifier/FontModifier.swift
  ForJaeRin/Global/Resources/SampleProject/sampleProject.json
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectHistoryVM.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputScriptView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryDashboardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryListView/ProjectHistoryListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Utils/DateManager.swift
Labels: Feat, Refactor

#92 키워드뷰 수정 전 PR
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/MissedKeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/PracticeSummaryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryDashboardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryListView/ProjectHistoryListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordFieldView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
Labels: Fix

#95 [Design]: 레이아웃 조정 - 1
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Extension/CGFloat+Extension.swift
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_1024.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_128.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_16.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_256 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_256.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_32 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_32.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_512 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_512.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/appLogo_64.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_1024.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_128.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_16.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_256 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_256.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_32 1.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_32.png
  ForJaeRin/Global/Resources/Assets.xcassets/AppIcon.appiconset/app_logo_64.png
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/HomeVM.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectDocumentVM.swift
  ForJaeRin/Presentation/Views/Components/PDFView/PDFView.swift
  ForJaeRin/Presentation/Views/Components/SectionHeaderView.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputScriptView.swift
  ForJaeRin/Presentation/Views/HomeView/ProjectCardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectFlowView/ProjectFlowView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListOnboardingView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
Labels: Design

#98 [Fix] 키워드 수정 저장,불러오기 오류 해결
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Models/ProjectModels/PracticeModel.swift
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ProjectCardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Utils/AppFileManager.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Fix

#100 [Design]: 연습 준비하기 페이지 레이아웃 수정
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Extension/CGFloat+Extension.swift
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/ProjectDocumentVM.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectFlowView/ProjectFlowView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryDashboardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
  ForJaeRin/Utils/AppFileManager.swift
Labels: Design

#101 presentationView Keyword 깨짐 해결
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Extension/View+Extension.swift
  ForJaeRin/Global/Modifier/ViewModifier.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Fix

#102 [Feat] 연습 기록 저장,불러오기 구현
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Feat

#103 keywordView fix
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/ViewModels/HomeVM/GroupListVM.swift
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/PieChartView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordFieldView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Utils/SpeechRecognizer.swift
Labels: Fix

#104 [Design]: ImportPDFView 레이아웃 정리 - 1
  ForJaeRin/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ForJaeRin/Presentation/ViewModels/ProjectVM/PresentationVM.swift
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationProgressView/PresentationProgressView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryDashboardView.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Design

#105 [Design]: 전반적인 레이아웃 간격 조정
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/ImportPDFVM.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/InputScriptVM.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/SettingGroupVM.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputScriptView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/KeywordListView/KeywordListView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectDocumentView/ProjectDocumentView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryDashboardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListOnboardingView.swift
Labels: Design

#107 [Feat] Metadata 수정
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Models/ProjectModels/ProjectMetadataModel.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryDashboardView.swift
  ForJaeRin/Utils/DateManager.swift
Labels: Feat

#110 키워드뷰 전면 수정
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordFieldView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/ProjectPlanView.swift
Labels: Fix

#111 [Feat] 이전 프로젝트 리스트에서 삭제 기능 구현
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryDashboardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/CustomBarChartView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/GroupChartView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/GroupView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/ProjectSummaryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectSummaryView/StyleDetailChartView.swift
  ForJaeRin/Utils/AppFileManager.swift
Labels: Feat

#112 presentationPlanList 키워드뷰
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
Labels: Fix

#115 [Feat]: FullScreenImageView 작성
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
Labels: Feat

#116 [Feat] 연습 기록 다시보기 화면으로 넘어가기
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/ProjectModels/ProjectFileManager.swift
  ForJaeRin/Presentation/Views/Components/FileSystemView/FileImporterButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/HomeView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/ImportPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/InputPresentationInfoView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationTimerView/PresentationTimerView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/PracticeSummaryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryDashboardView.swift
  ForJaeRin/Utils/AppFileManager.swift
  ForJaeRin/Utils/VoiceManager.swift
Labels: Feat

#117 [Design]: ProjectPlanView 레이아웃 조정
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Presentation/ViewModels/ProjectVM/FullScreenImageView.swift
  ForJaeRin/Presentation/Views/HomeView/ProjectCardView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/Keyword/KeywordView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageList.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListItem.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectPlanView/PresentationPageList/PresentationPageListOnboardingView.swift
Labels: Design

#118 그룹화하기 끝
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Models/PDFModels/MyData.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/GroupListVM.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/ImportPDFVM.swift
  ForJaeRin/Presentation/ViewModels/HomeVM/SettingGroupVM.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupListView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/GroupingAddButtonView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/GroupComponentView/TempPDFView.swift
  ForJaeRin/Presentation/Views/HomeView/ImportPDFView/SettingGroupView.swift
  ForJaeRin/Presentation/Views/ProjectView/ProjectHistoryView/ProjectHistoryView.swift
Labels: Fix

#127 [Fix]: PDF 이미지 확대뷰가 화면을 넘어가는 현상 수정
  ForJaeRin.xcodeproj/project.pbxproj
  ForJaeRin/Global/Resources/Assets.xcassets/presentationOnboarding.imageset/Contents.json
  ForJaeRin/Global/Resources/Assets.xcassets/presentationOnboarding.imageset/presentationOnboarding.png
  ForJaeRin/Presentation/ViewModels/ProjectVM/FullScreenImageView.swift
  ForJaeRin/Presentation/ViewModels/ProjectVM/PresentationVM.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationOnboardingView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/PresentationView.swift
  ForJaeRin/Presentation/Views/ProjectView/PresentationView/VoiceVisualizationView/VoiceVisualizationView.swift
Labels: Fix
